apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus-operated:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: trace_id
          matcherRegex: '"trace_id":"([a-f0-9]+)"'
          url: '$${__value.raw}'
          datasourceUid: tempo

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        customQuery: true
        query: '{service="tasklog-api"} |= "$${__span.traceId}"'

  - name: Postgres
    uid: pg
    type: postgres
    access: proxy
    url: pg.tasklog.svc.cluster.local:5432
    user: monitor
    secureJsonData:
      password: $PG_MONITOR_PASSWORD
    jsonData:
      database: tasklog
      sslmode: disable
      postgresVersion: 1600
