services:
  pg:
    image: postgres:16.10-alpine
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "pg_stat_statements.track=all"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tasklog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tasklog}
      POSTGRES_DB: ${POSTGRES_DB:-tasklog}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./deploy/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasklog -d tasklog"]
      interval: 5s
      timeout: 3s
      retries: 12

  api:
    image: ghcr.io/${GHCR_OWNER:-raflyritonga}/tasklog-api:${IMG_TAG:-dev}
    build: ./app/api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-tasklog}:${POSTGRES_PASSWORD:-tasklog}@pg:5432/${POSTGRES_DB:-tasklog}?sslmode=disable
      REDIS_ADDR: redis:6379
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    image: ghcr.io/${GHCR_OWNER:-raflyritonga}/tasklog-web:${IMG_TAG:-dev}
    build: ./app/web
    environment:
      NUXT_API_PROXY_TARGET: http://api:8080
      NUXT_PUBLIC_RUM_PROVIDER: ${NUXT_PUBLIC_RUM_PROVIDER:-datadog}
      NUXT_PUBLIC_DD_SITE: ${DD_SITE:-}
      NUXT_PUBLIC_DD_RUM_APP_ID: ${DD_RUM_APP_ID:-}
      NUXT_PUBLIC_DD_RUM_CLIENT_TOKEN: ${DD_RUM_CLIENT_TOKEN:-}
      NUXT_PUBLIC_DT_RUM_SCRIPT_URL: ${DT_RUM_SCRIPT_URL:-}
      NUXT_PUBLIC_ELASTIC_APM_ENDPOINT: ${ELASTIC_APM_ENDPOINT:-}
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/"]
      interval: 5s
      timeout: 3s
      retries: 12
    depends_on:
      - api

  redis:
    image: redis:7.4.5-alpine
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 12

volumes:
  pg-data:
