apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasklog
  namespace: tasklog
spec:
  ingressClassName: traefik
  rules:
    - host: tasklog-demo.orb.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /readyz
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
