nodeSelector:
  ingress-ready: "true"

ports:
  web:
    hostPort: 80
  websecure:
    hostPort: 443

service:
  type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
