nodeSelector:
  ingress-ready: "true"

ports:
  web:
    hostPort: 80
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
  websecure:
    hostPort: 443
    forwardedHeaders:
      trustedIPs:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16

service:
  type: ClusterIP

ingressClass:
  enabled: true
  isDefaultClass: true

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
