apiVersion: dynatrace.com/v1beta5
kind: DynaKube
metadata:
  name: tasklog
  namespace: dynatrace
spec:
  apiUrl: __DT_API_URL__
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      namespaceSelector:
        matchLabels:
          dynatrace-inject: enabled
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
