
[sinks.elastic]
type = "elasticsearch"
inputs = ["parsed"]
endpoints = ["__ELASTIC_ES_ENDPOINT__"]
api_version = "auto"
mode = "bulk"

[sinks.elastic.bulk]
action = "create"
index = "logs-tasklog-default"

[sinks.elastic.auth]
strategy = "basic"
user = "__ELASTIC_ES_USER__"
password = "__ELASTIC_ES_PASSWORD__"
