apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: o11y
spec:
  version: 9.5.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  config:
    server.publicBaseUrl: http://kibana.tasklog-demo.orb.local
    xpack.apm.indices.transaction: traces-apm*,apm-*,traces-*.otel-*
    xpack.apm.indices.span: traces-apm*,apm-*,traces-*.otel-*
    xpack.apm.indices.error: logs-apm*,apm-*,logs-*.otel-*
    xpack.apm.indices.metric: metrics-apm*,apm-*,metrics-*.otel-*
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 1536Mi
