// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/21/2026, 5:50:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/rafly/workspace/lab/tasklog/app/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/plugins/**/*.{js,ts,mjs}","/Users/rafly/workspace/lab/tasklog/app/web/composables/**/*.{js,ts,mjs}","/Users/rafly/workspace/lab/tasklog/app/web/utils/**/*.{js,ts,mjs}","/Users/rafly/workspace/lab/tasklog/app/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rafly/workspace/lab/tasklog/app/web/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;