name: ci

on:
  push:
    branches:
      - datadog

permissions:
  contents: read
  packages: write

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: sha
        run: echo "short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          context: app/api
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=sha-${{ steps.sha.outputs.short }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/tasklog-api:datadog
            ghcr.io/${{ github.repository_owner }}/tasklog-api:sha-${{ steps.sha.outputs.short }}
          cache-from: type=gha,scope=api-datadog
          cache-to: type=gha,scope=api-datadog,mode=max

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: sha
        run: echo "short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          context: app/web
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=sha-${{ steps.sha.outputs.short }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/tasklog-web:datadog
            ghcr.io/${{ github.repository_owner }}/tasklog-web:sha-${{ steps.sha.outputs.short }}
          cache-from: type=gha,scope=web-datadog
          cache-to: type=gha,scope=web-datadog,mode=max

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: sha
        run: echo "short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v6
        with:
          context: app/report
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=sha-${{ steps.sha.outputs.short }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/tasklog-report:datadog
            ghcr.io/${{ github.repository_owner }}/tasklog-report:sha-${{ steps.sha.outputs.short }}
          cache-from: type=gha,scope=report-datadog
          cache-to: type=gha,scope=report-datadog,mode=max
