init_config:

instances:
  - host: pg
    port: 5432
    username: monitor
    password: "%%env_PG_MONITOR_PASSWORD%%"
    dbname: tasklog
    dbm: true
    collect_schemas:
      enabled: true
    query_samples:
      enabled: true
    query_metrics:
      enabled: true
    relations:
      - relation_regex: .*
    tags:
      - env:dev
      - project:tasklog
